<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lead Source Report - PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            margin-bottom: 30px;
        }
        .summary h3 {
            color: #333;
            margin-bottom: 15px;
        }
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
            margin-bottom: 20px;
        }
        .summary-item {
            text-align: center;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
        .summary-item h4 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .summary-item p {
            margin: 5px 0 0 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Lead Source Report</h1>
        <p>Report Period: {{ \Carbon\Carbon::parse($fromDate)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($toDate)->format('M d, Y') }}</p>
        <p>Generated on: {{ now()->format('M d, Y H:i:s') }}</p>
    </div>

    <div class="summary">
        <h3>Report Summary</h3>
        <div class="summary-grid">
            <div class="summary-item">
                <h4>{{ $reports['lead_source']->sum('count') }}</h4>
                <p>Total Leads</p>
            </div>
            <div class="summary-item">
                <h4>{{ $reports['lead_source']->count() }}</h4>
                <p>Lead Sources</p>
            </div>
            <div class="summary-item">
                <h4>{{ $reports['lead_source']->max('count') }}</h4>
                <p>Highest Source</p>
            </div>
            <div class="summary-item">
                <h4>{{ $reports['lead_source']->avg('count') }}</h4>
                <p>Average per Source</p>
            </div>
        </div>
    </div>

    <div class="summary">
        <h3>Lead Source Report</h3>
        <table>
            <thead>
                <tr>
                    <th>Source</th>
                    <th>Count</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reports['lead_source'] as $source)
                    @php
                        $total = $reports['lead_source']->sum('count');
                        $percentage = $total > 0 ? round(($source->count / $total) * 100, 1) : 0;
                    @endphp
                    <tr>
                        <td>{{ $source->title }}</td>
                        <td>{{ $source->count }}</td>
                        <td>{{ $percentage }}%</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    @if($reports['monthly']->count() > 0)
    <div class="summary">
        <h3>Monthly Trend</h3>
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Total Leads</th>
                    <th>Converted</th>
                    <th>Conversion Rate</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reports['monthly'] as $month)
                    <tr>
                        <td>{{ $month->month }}</td>
                        <td>{{ $month->total_leads > 0 ? $month->total_leads : '-' }}</td>
                        <td>{{ $month->converted > 0 ? $month->converted : '-' }}</td>
                        <td>{{ $month->total_leads > 0 ? $month->conversion_rate . '%' : '0%' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>Generated by CRM System on {{ now()->format('M d, Y H:i:s') }}</p>
    </div>
</body>
</html>
