{{-- Terms & Conditions checkbox (place last before submit button) and modal --}}
<div class="form-group mt-3 mb-3" id="termsCheckboxRow" style="display: none;">
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="terms_accepted" id="termsCheckbox" value="1" disabled>
        <label class="form-check-label" for="termsCheckbox">
            I agree to the <a href="#" id="termsLink" data-bs-toggle="modal" data-bs-target="#termsModal">Terms and Conditions</a>
        </label>
    </div>
    <small class="text-muted d-block mt-1">You must open and scroll through the full Terms and Conditions before you can accept and submit.</small>
</div>

<!-- Terms & Conditions Modal -->
<div class="modal fade" id="termsModal" tabindex="-1" aria-labelledby="termsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="termsModalLabel">TERMS &amp; CONDITIONS</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="termsModalBody" style="max-height: 70vh; overflow-y: auto;">
                <div class="terms-content">
                    <h6>SECTION 1 — ADMISSION AUTHORITY & ELIGIBILITY VERIFICATION</h6>
                    <p>All admissions granted by the institution shall be deemed strictly provisional until final verification and approval have been completed in accordance with institutional standards and, where applicable, the requirements of governing academic boards, certification bodies, universities, or regulatory authorities having jurisdiction over the program. Submission of an application or fulfillment of minimum eligibility criteria shall not create any entitlement to admission, and the institution reserves absolute discretionary authority to approve, reject, defer, or cancel any application without obligation to disclose reasons unless disclosure is mandated by law. Admission decisions shall be based on comprehensive evaluation of documentation, eligibility, authenticity of records, conduct assessment, compliance with institutional requirements, and availability of seats, and institutional determination in this regard shall be final and binding. If at any stage it is discovered that a student has provided inaccurate, incomplete, misleading, or unverifiable information, or has failed to meet eligibility requirements, or has submitted documents later found to be invalid, forged, or inconsistent, the institution shall have the unrestricted right to cancel admission with immediate effect without liability or obligation to provide compensation. Admission rights are personal to the applicant and shall not be transferable, assignable, or substitutable under any circumstances. Students acknowledge that admission constitutes a privilege granted subject to institutional evaluation rather than a guaranteed right and agree to comply with all verification procedures required to confirm eligibility.</p>

                    <h6>SECTION 2 — DOCUMENTATION COMPLIANCE</h6>
                    <p>Students shall be required to submit complete, accurate, and verifiable documentation as prescribed by the institution for purposes including identity verification, eligibility confirmation, registration processing, academic record maintenance, certification issuance, and regulatory compliance, and such documentation may include government-recognized identification proof, academic certificates, photographs, declarations, and any additional records requested by the institution or governing authorities. Submission of forged, altered, manipulated, incomplete, or unverifiable documents shall constitute a serious violation of institutional policy and may result in immediate cancellation of admission, permanent disqualification from institutional programs, and reporting to relevant authorities where required. The institution reserves full authority to authenticate submitted documents through verification mechanisms, and students agree to cooperate with such verification procedures. The institution shall not be responsible for rejection of registration, certification, or eligibility approval by external authorities where such rejection results from deficiencies in student-submitted documentation. Responsibility for authenticity and accuracy of documents rests solely with the student. Institutional records regarding document submission and verification status shall constitute definitive evidence in any dispute. Failure to submit required documents within prescribed timelines may result in suspension of services or cancellation of enrollment. This section establishes strict compliance obligations relating to documentation and ensures integrity of academic and administrative processes.</p>

                    <h6>SECTION 3 — REGISTRATION WITH BOARDS / UNIVERSITIES / AUTHORITIES</h6>
                    <p>Registration of students with external boards, universities, examination authorities, or regulatory bodies shall be initiated only after the institution confirms receipt of complete documentation and full or required fee payment as per applicable rules, and students expressly acknowledge that processing timelines, approval decisions, and confirmation of registration are determined solely by such external authorities and not by the institution. The institution may act as a facilitation entity responsible for forwarding applications and required data; however, it shall not guarantee approval, processing speed, or outcome of registration requests. Students agree that delays caused by authority systems, technical issues, policy revisions, or administrative procedures of external bodies shall not create liability for the institution. Requests for corrections or modifications after submission to authorities shall be subject to applicable charges and authority approval. The institution shall not be responsible for rejection of registration by governing bodies where rejection results from factors beyond institutional control. Students acknowledge that authority decisions are final and binding. Institutional responsibility shall be limited to accurate submission of information provided by students, and the institution shall not be liable for consequences arising from incorrect information supplied by the student. This section clarifies the facilitative nature of institutional involvement in external registrations.</p>

                    <h6>SECTION 4 - REFUND & ACCOUNT POLICY</h6>
                    <p>This Refund & Account Policy sets forth the detailed terms under which fees paid to the institution are considered for refund, as well as the conditions under which student accounts may be discontinued or reactivated. By proceeding with admission, students and guardians acknowledge their understanding and acceptance of this policy.</p>
                    <p><strong>Admission Fee</strong><br>The admission fee is a mandatory, one-time charge that is collected from every student at the very beginning of the enrollment process. This payment is not merely a formality — it is an essential requirement for initiating the administrative workflow associated with bringing a new student into the system. Once this fee is paid, several critical steps are immediately triggered by the institution's administrative team, including but not limited to: Creating and verifying the student's admission record in the institutional database; Processing and confirming the admission application; Allocating the student a place within the selected program or course; Setting up the student's digital account and enabling access to the learning platform; Coordinating with relevant internal departments to ensure the smooth start of classes and communication. Because these processes are carried out instantly and incur direct administrative costs, the admission fee is considered strictly non-refundable under all circumstances. This means that even if the student later decides to withdraw voluntarily, discontinue participation due to personal reasons, or request a transfer to another program or institution, the admission fee will not be refunded. This non-refundable policy applies equally in cases where: The student fails to complete the enrollment process after payment; The student delays document submission beyond allowed timelines; The student does not attend any classes despite admission confirmation. In summary, the admission fee secures the student's entry into the institution and covers the foundational work required to officially begin their academic journey. Since the associated expenses are incurred immediately and cannot be reversed, the fee remains fully non-refundable once paid.</p>
                    <p><strong>Registration Fee</strong><br>The registration fee is a compulsory payment that is charged after the admission fee has been paid and is specifically intended to finalize the student's enrollment with all relevant academic bodies. Unlike the admission fee, which is primarily for internal administrative processing, the registration fee directly covers official charges such as board fees, university fees, or other statutory charges that are necessary to formally register the student under the chosen curriculum or examination board. This payment is crucial because it ensures that: The student's name is officially submitted to the respective educational board or university; Mandatory government fees and regulatory charges are cleared on behalf of the student; The student is eligible to sit for board/university examinations or assessments as per the academic calendar; The institution can begin necessary coordination with academic authorities to secure enrollment confirmation. It is important to note that the registration fee is considered purely a government and statutory payment. Since the institution simply acts as an intermediary to collect and remit these funds to the appropriate board or university, this amount is strictly non-refundable under any circumstances. Furthermore, no refund will be processed if: The student fails to provide the required documents within the specified timelines, which results in a delay or inability to complete the registration process; The documents submitted by the student are found to be incomplete, inaccurate, or invalid; The student or guardian fails to respond in a timely manner to communication from the registration team; The student provides misleading, false, or misrepresented information during the admission process, resulting in rejection by the board/university. Since these payments are transmitted to third-party government or academic bodies on behalf of the student, the institution has no authority to recall or recover them once remitted. For this reason, registration fees remain entirely non-refundable even in the event of withdrawal, cancellation, or discontinuation of the program by the student.</p>
                    <p><strong>Exam Fee</strong><br>The exam fee is a specific payment charged to cover the cost of enrolling the student for assessments, examinations, and evaluation processes associated with their chosen subjects or program of study. This fee is directly linked to the number of subjects that a student chooses to take during a given academic term or examination cycle. Because examination-related charges are often regulated by the respective board or university, the total payable amount may vary based on: The total number of subjects the student has opted for; The inclusion of any additional subjects after the initial enrollment; Changes in fee structures announced by the governing educational body. Once paid, the exam fee is utilized for: Registering the student for the appropriate examination session with the board/university; Covering administrative charges related to preparing hall tickets/admit cards; Ensuring timely communication of examination schedules and important updates; Coordinating with external authorities for smooth participation in the assessment process. Since this fee is remitted to external academic bodies on behalf of the student, it is strictly non-refundable once the payment and registration process is completed. This rule applies even if: The student later decides to withdraw from the course or examination; The student chooses not to appear for one or more examinations; The student fails to qualify to appear for the examination due to insufficient attendance or non-fulfillment of internal academic requirements. In short, the exam fee is dedicated exclusively to examination-related formalities and cannot be reversed or credited back once processed. Students are therefore advised to carefully confirm the number of subjects they wish to register for before making payment, as adjustments or refunds will not be entertained thereafter.</p>
                    <p><strong>Tuition Fee & Course Fee</strong><br>The tuition fee and course fee constitute the charges payable by the student/guardian for the provision of mentoring services, faculty guidance, academic resources, learning materials, and other educational support made available by the institution. This component is distinct and separate from admission fees, registration fees, and examination fees. The amount is determined and charged only after the admission, registration, and exam fees have been collected in full. In circumstances where a student chooses to withdraw from the program after payment of the tuition/course fee, the institution shall process the refund in strict accordance with the following schedule: Within 48 hours of admission date: 100% refund of tuition & course fee shall be granted, subject to administrative verification. Nil deduction. Within 10 days of admission date: 70% of the tuition & course fee shall be refunded; 30% will be retained towards mentoring and administrative charges. Within 30 days of admission date: 50% refund shall be processed; the remaining 50% will be retained to cover the cost of faculty allocation, digital resources, and mentoring services already rendered. Within 60 days of admission date: 25% refund shall be processed; 75% will be retained on account of consumed services and administrative overheads. Additional Clarifications: (a) No Refund After 60 Days: For the avoidance of doubt, no refund of tuition or course fee shall be entertained beyond 60 days from the admission date, irrespective of attendance or participation status. (b) Definition of Admission Date: For the purpose of this policy, admission date shall mean the calendar date on which the student has (i) completed the full payment due, and (ii) submitted all required documents to the satisfaction of the institution. Only after both these conditions are fulfilled shall the admission date be considered final. (c) Exclusion of Registration & University Charges: The refund schedule mentioned above is strictly applicable only to tuition and course fees. It specifically excludes any registration fees, board/university charges, or examination fees which are, by their nature, non-refundable. (d) Final Date Payments: If the student completes the payment during the final days of the admission window and the institution has already remitted registration or university fees on their behalf, those fees shall remain strictly non-refundable. Only the tuition/course fee component shall be considered for refund as per the above table. (e) Institution's Final Authority: The institution reserves the exclusive right to determine the exact amount of refund payable after adjusting for services rendered. This decision shall be considered final and binding on the student and guardian.</p>
                    <p><strong>Additional Subjects</strong><br>In the event that a student decides to enroll in additional subjects after their initial admission has been confirmed, the institution reserves the right to revise and update all applicable charges. Any amount paid towards the enrollment of additional subjects is considered strictly non-refundable once the enrollment has been confirmed by the institution. Students are therefore advised to finalize their decision carefully before requesting the addition of subjects, as no refund or adjustment will be possible once the enrollment confirmation is issued.</p>
                    <p><strong>GST & Other Statutory Charges</strong><br>All payments made by the student, including admission fees, registration fees, exam fees, and tuition/course fees, are inclusive of GST (Goods and Services Tax) or any other statutory tax that may be levied by the Government of India from time to time. If there is any change in tax rates (increase or decrease) notified by the government during the course of a student's enrollment, such changes shall automatically apply to all pending or future payments.</p>
                    <p><strong>Account Discontinuation / Reactivation / Mode of Refund / Processing Time / Notification</strong><br>Failure to make payments within the stipulated timelines will result in the temporary suspension or discontinuation of the student's access. Students whose accounts have been discontinued due to non-payment of dues may request reactivation by paying all pending dues and any applicable reactivation fee. Refunds, wherever applicable, will be processed exclusively through bank transfer to the account details provided by the student or guardian. The institution will process refunds within a reasonable timeline, generally within 7 working days from the date of approval. By making any payment to the institution, the student and guardian acknowledge that they have read, understood, and agreed to the terms of this Refund Policy.</p>

                    <h6>SECTION 5 — ACADEMIC DELIVERY FRAMEWORK</h6>
                    <p>The institution reserves full authority to design, structure, modify, and deliver academic programs in accordance with pedagogical standards, regulatory requirements, operational feasibility, and academic strategy, and students expressly acknowledge that academic delivery parameters including trainers, faculty members, schedules, syllabi, teaching methodology, digital platforms, learning tools, batch structures, evaluation formats, and course timelines may be revised whenever necessary. Such modifications shall not be construed as breach of commitment provided the institution continues to deliver the academic program in a reasonable and academically valid manner. The institution does not guarantee individual academic performance, examination success, or specific outcomes, as results depend upon student effort, participation, and ability. Students agree to follow academic instructions, attend sessions, complete assignments, and comply with academic requirements as communicated. The institution shall not be responsible for academic underperformance arising from student negligence or non-participation. Where technological platforms are used, access shall depend on system availability and student compliance with technical requirements. Institutional academic records shall constitute authoritative evidence of participation and performance. This section establishes institutional authority over academic delivery and clarifies that program structure may evolve to maintain quality and compliance.</p>

                    <h6>SECTION 6 — ATTENDANCE & PARTICIPATION COMPLIANCE</h6>
                    <p>Attendance and active participation in all academic activities designated as mandatory by the institution shall constitute a fundamental academic obligation binding upon every enrolled student, irrespective of program mode, duration, or delivery format, and students expressly acknowledge that compliance with prescribed attendance requirements is a prerequisite for academic eligibility, evaluation participation, certification processing, and continuation of enrollment. The institution reserves full authority to determine minimum attendance thresholds, methods of recording attendance, and criteria for participation evaluation, which may include digital logs, biometric systems, platform access records, faculty registers, or automated monitoring systems, and such institutional records shall be treated as final and conclusive evidence of attendance status. Failure to meet prescribed attendance levels may result in academic warnings, mentoring intervention, suspension of services, examination ineligibility, or termination of enrollment, depending on severity and frequency of absence. Absence for personal, professional, medical, or logistical reasons shall not automatically qualify for exemption unless supported by verifiable documentation and formally approved by authorized institutional authorities. The institution shall not be obligated to provide compensation classes, rescheduling, or alternative arrangements for missed sessions unless expressly provided under program policy. Repeated absenteeism or prolonged inactivity may be treated as academic disengagement. Students agree that responsibility for maintaining attendance rests solely with them and that institutional enforcement of attendance standards is essential for academic integrity and regulatory compliance.</p>

                    <h6>SECTION 7 — ASSIGNMENTS, ASSESSMENTS & EVALUATION</h6>
                    <p>Students shall be required to complete and submit all assignments, assessments, projects, examinations, or academic exercises prescribed as part of their program within stipulated timelines and in accordance with institutional instructions, and such academic tasks shall constitute integral components of evaluation designed to measure comprehension, analytical ability, practical application, and academic discipline. The institution reserves full authority to determine assessment methods, grading criteria, submission formats, and evaluation standards and may revise such parameters where necessary for academic or regulatory reasons. Late submissions may be rejected unless formally approved, and evaluation outcomes determined by authorized academic personnel shall be final and binding except where official review procedures exist. Academic misconduct including plagiarism, copying, impersonation, fabrication of data, or unauthorized assistance shall be treated as serious violations and may result in penalties ranging from mark deduction to termination of enrollment. Students acknowledge that evaluation results depend solely on individual performance and shall not be disputed on subjective grounds. Requests for re-evaluation shall be considered only where formal mechanisms exist and must be submitted within prescribed timelines. Institutional evaluation records shall constitute definitive evidence of academic performance. This section establishes academic accountability and ensures fairness in assessment procedures.</p>

                    <h6>SECTION 8 — EXAMINATION GOVERNANCE</h6>
                    <p>All examinations associated with institutional programs shall be conducted in accordance with rules prescribed either by the institution or by relevant governing authorities, and students expressly acknowledge that examination schedules, formats, eligibility criteria, and procedural requirements are determined exclusively by competent authorities and may be modified at any time without prior notice where necessary. Participation in examinations shall be conditional upon fulfillment of eligibility requirements including attendance compliance, assignment completion, fee clearance, and adherence to institutional regulations. Students shall comply strictly with examination instructions, reporting times, identification requirements, permitted materials, and behavioral standards, and any violation may result in disqualification or disciplinary action. The institution reserves the right to monitor examinations through invigilation, digital proctoring, or surveillance mechanisms, and students consent to such monitoring as a condition of participation. Malpractice or misconduct shall be subject to penalties including cancellation of results or reporting to authorities. The institution shall not be liable for postponements or cancellations caused by external authorities or circumstances beyond control. Examination results issued by competent authorities shall be final. This section ensures integrity, fairness, and regulatory compliance in examination processes.</p>

                    <h6>SECTION 9 — CERTIFICATION ISSUANCE POLICY</h6>
                    <p>Certificates, transcripts, or completion documents shall be issued only upon fulfillment of all academic, administrative, financial, and regulatory requirements prescribed by the institution or relevant governing authority, and students expressly acknowledge that certification is not automatic upon enrollment or fee payment but is contingent upon successful completion of program requirements and verification of eligibility. The institution reserves full authority to verify academic records, attendance data, assessment results, and financial clearance prior to initiating certification processing, and certificates may be withheld until deficiencies are resolved. Where certification is issued by external authorities, timelines shall depend entirely on those bodies and the institution shall not be liable for delays. Lost certificates may be reissued only upon submission of formal request and payment of prescribed fees. The institution shall not be responsible for delays caused by third parties, postal services, or authority processing. Students acknowledge that certification is an official validation of achievement and must therefore be issued under controlled verification procedures. Institutional records shall constitute conclusive evidence of eligibility status. This section defines conditions and limitations governing certificate issuance.</p>

                    <h6>SECTION 10 — BATCH INTEGRITY POLICY</h6>
                    <p>Students admitted to any program shall be assigned to a specific batch determined by the institution based on operational capacity, scheduling, curriculum sequencing, and administrative planning, and such batch allocation shall remain binding throughout the program duration unless formally changed through authorized procedures. Participation in sessions of other batches without approval shall not be recognized for academic credit. Requests for batch transfer must be submitted through official channels and shall be approved only under exceptional circumstances at institutional discretion. Approved transfers may require payment of a non-refundable administrative fee and compliance with additional academic requirements to align with the new batch schedule. The institution reserves the right to restructure or merge batches where necessary and such changes shall be binding. Institutional records shall constitute definitive evidence of batch allocation. Students acknowledge that batch integrity is essential for synchronized learning, accurate tracking, and administrative efficiency and therefore agree to participate only within their designated cohort. This section safeguards structured academic delivery.</p>

                    <h6>SECTION 11 — DIGITAL PLATFORM & ACCESS POLICY</h6>
                    <p>Access to institutional digital platforms including learning applications, portals, virtual classrooms, and online resources shall be granted solely for academic purposes and shall remain conditional, non-transferable, and revocable at the institution's discretion. Students shall maintain confidentiality of login credentials and shall be responsible for all activity conducted through their accounts. Sharing access details or attempting unauthorized entry into restricted systems shall constitute a policy violation. The institution reserves the right to monitor platform usage, login activity, and system interactions for security and compliance purposes, and students consent to such monitoring. Availability of digital platforms depends on technological infrastructure and may be interrupted due to maintenance or technical issues beyond institutional control. The institution shall not be liable for service interruptions or technical limitations on the student's side. All digital content remains institutional intellectual property and may not be copied, distributed, or shared without authorization. Access privileges may be suspended where misuse is detected. Institutional system logs shall constitute definitive evidence in disputes. This section defines rules governing use of institutional technology resources.</p>

                    <h6>SECTION 12 — COMMUNICATION COMPLIANCE PROTOCOL</h6>
                    <p>All official communication between the institution and students shall be conducted exclusively through authorized institutional channels, which may include registered email addresses, official mobile numbers, institutional applications, learning platforms, designated communication groups, or other formally approved systems, and students expressly acknowledge that only communications transmitted through such channels shall be considered valid, binding, and legally recognized. The institution reserves full authority to determine, modify, or replace communication channels as necessary, and students shall ensure that their registered contact information remains accurate and active at all times. Failure to maintain updated contact details or to review messages regularly shall not exempt students from compliance with instructions or deadlines communicated through official channels. Communication records, delivery logs, or system notifications maintained by the institution shall constitute conclusive evidence that communication has been issued. Students shall use institutional communication platforms responsibly and professionally and shall refrain from posting irrelevant, offensive, defamatory, or unauthorized content. Misuse of communication channels may result in disciplinary action or restriction of access. The institution shall not be responsible for missed information resulting from negligence, muted notifications, or failure to review official messages. This section establishes communication accountability and ensures orderly academic coordination.</p>

                    <h6>SECTION 13 — MENTORSHIP GOVERNANCE</h6>
                    <p>The institution may assign each student a designated mentor or academic advisor responsible for providing academic guidance, monitoring progress, offering study strategies, and supporting structured learning, and students expressly acknowledge that such mentorship is an academic support mechanism rather than a guarantee of academic success or a substitute for personal effort. Mentor allocation shall be determined solely by the institution based on operational considerations and may be changed at any time without prior notice. Students shall cooperate with mentor instructions, respond to communications in a timely manner, and maintain professional conduct during all mentoring interactions. Mentors operate within institutional policies and therefore cannot modify rules, grant concessions, or approve requests beyond their authorized scope. Failure to engage with mentorship processes or repeated non-responsiveness may be treated as academic disengagement. The institution may monitor mentoring interactions for quality assurance and compliance purposes, and students consent to such monitoring. Mentoring reports or progress evaluations generated by the institution shall be used for academic improvement purposes and shall not constitute formal certification of competence. Institutional records shall serve as definitive evidence of mentoring support provided. This section clarifies the role, limits, and expectations of mentorship support systems.</p>

                    <h6>SECTION 14 — CODE OF CONDUCT & DISCIPLINE</h6>
                    <p>Students shall maintain professional, respectful, ethical, and disciplined behavior at all times while associated with the institution, whether in physical premises, digital environments, communication platforms, or academic events, and any conduct that disrupts academic order, violates institutional standards, or compromises safety or integrity shall constitute misconduct subject to disciplinary action. Prohibited conduct includes abusive language, harassment, intimidation, academic dishonesty, unauthorized recording, impersonation, damage to property, system misuse, or any behavior deemed inappropriate by the institution. The institution reserves full authority to classify conduct as unacceptable and to impose disciplinary measures proportionate to the severity of violation, including warnings, suspension of privileges, academic probation, termination of enrollment, or reporting to authorities where required. Students shall cooperate fully with disciplinary investigations and provide accurate information when requested. Institutional decisions regarding disciplinary action shall be final and binding. Institutional records shall constitute authoritative evidence in disputes relating to conduct. This section ensures maintenance of a safe, respectful, and academically focused environment.</p>

                    <h6>SECTION 15 — INTELLECTUAL PROPERTY RIGHTS</h6>
                    <p>All academic materials, content, methodologies, digital resources, and instructional assets provided by the institution shall remain the exclusive intellectual property of the institution or its licensors and shall be protected under applicable intellectual property laws, and students expressly acknowledge that access to such materials grants only a limited license for personal educational use without conferring ownership or distribution rights. Students shall not copy, record, distribute, reproduce, sell, publish, or share institutional content without prior written authorization. Unauthorized use of academic materials, recording of sessions, or sharing of resources shall constitute infringement and may result in disciplinary or legal action. The institution reserves the right to employ monitoring technologies to detect unauthorized use. Student-submitted academic work may be retained or used by the institution for academic or quality assurance purposes, provided appropriate attribution standards are followed. Students shall not use institutional branding, logos, or identity for personal promotion without authorization. Institutional determination regarding intellectual property violations shall be final. This section protects institutional content rights and ensures ethical usage.</p>

                    <h6>SECTION 16 — PRIVACY & DATA PROTECTION</h6>
                    <p>The institution shall collect, store, and process student data solely for legitimate academic, administrative, regulatory, and operational purposes, and students expressly consent to such processing upon submission of personal information. Data collected may include identification details, academic records, contact information, attendance data, financial information, and system usage logs, all of which shall be maintained securely with restricted access. The institution may share necessary data with governing authorities, examination bodies, or service providers where required for academic processing or compliance, and students consent to such sharing. The institution shall not sell personal data for commercial purposes. Students are responsible for ensuring accuracy of submitted information and must promptly update any changes. The institution may retain student records for periods required by law or administrative necessity. While reasonable safeguards shall be implemented to protect data, the institution shall not be liable for breaches arising from circumstances beyond its control. Institutional data records shall constitute definitive evidence in disputes relating to information handling. This section defines privacy standards and data usage principles.</p>

                    <h6>SECTION 17 — PARTNER / FRANCHISE ADMISSIONS CLAUSE</h6>
                    <p>Admissions processed through partners, franchise centers, consultants, or external representatives shall remain fully governed by institutional policies, and students expressly acknowledge that such intermediaries act only as facilitators without authority to modify institutional rules or make binding commitments. The institution retains exclusive authority over admission approval, fee determination, eligibility verification, and enrollment confirmation, and any assurances made by partners shall not be binding unless confirmed in writing by the institution. Students must verify payment instructions directly with the institution, as it shall not be responsible for unauthorized payments made to third parties. The institution shall not be liable for misrepresentations, promises, or guarantees made by external agents. Partner authorization status may change at any time, and students must verify legitimacy before engaging with intermediaries. Institutional records shall prevail over any conflicting statements made by partners. Complaints regarding partner conduct must be reported through official channels. This section clarifies responsibility boundaries between the institution and third-party facilitators.</p>

                    <h6>SECTION 18 — GRIEVANCE REDRESSAL FRAMEWORK</h6>
                    <p>The institution maintains a structured grievance redressal mechanism through which students may submit complaints, concerns, or requests for review relating to academic, administrative, financial, or service matters, and students expressly acknowledge that only grievances submitted through officially designated channels shall be recognized as valid for institutional consideration. The institution reserves full authority to define submission procedures, documentation requirements, timelines, and evaluation criteria for grievance handling, and incomplete or unsupported complaints may be declined. Upon receipt of a valid grievance, the institution shall review the matter through internal processes including record verification and consultation with relevant departments, and resolution timelines shall depend on complexity of the issue. Students shall cooperate fully with requests for clarification or additional information. Dissatisfied students may escalate grievances through prescribed hierarchy within specified timeframes, and decisions rendered at final escalation level shall be binding. Frivolous or malicious complaints may be rejected or treated as conduct violations. Institutional records shall constitute conclusive evidence in grievance-related disputes. This section establishes a formal, structured system for fair resolution of concerns.</p>

                    <h6>SECTION 19 — OPERATIONAL HOURS POLICY</h6>
                    <p>The institution shall operate within officially declared working hours during which administrative services, academic support, and communication responses shall be provided, and students expressly acknowledge that institutional obligations to respond arise only within such operational hours. Communications received outside working hours shall be deemed received on the next official working day for processing purposes. The institution reserves authority to modify working hours, declare holidays, or suspend operations temporarily due to administrative, regulatory, or unforeseen circumstances. Response timelines shall be calculated based on working hours rather than calendar time, and delays caused by high communication volume or operational constraints shall not constitute service deficiency. Students must plan submissions and requests within official hours and shall not claim exemption for delays caused by last-minute actions. Institutional timestamp records shall constitute definitive evidence of submission timing. This section ensures clarity regarding service availability and administrative scheduling.</p>

                    <h6>SECTION 20 — FORCE MAJEURE & LIABILITY LIMITATION</h6>
                    <p>The institution shall not be liable for failure or delay in performing obligations where such delay arises from events beyond reasonable control including natural disasters, governmental actions, technological failures, public emergencies, or other force majeure circumstances, and students expressly acknowledge that such events may necessitate suspension, postponement, or modification of academic activities without prior notice. The institution may adopt alternative arrangements such as schedule changes or delivery mode adjustments to maintain continuity, and such actions shall not constitute breach of commitment. Total institutional liability for any claim shall be limited to the amount of fees actually paid by the student for the program, and under no circumstance shall the institution be liable for indirect or consequential damages. Students agree to indemnify the institution against claims arising from their own misconduct or violations. Institutional determination regarding applicability of force majeure shall be final. This section defines liability boundaries and protects institutional operations against extraordinary disruptions.</p>

                    <h6>SECTION 21 — POLICY AMENDMENT AUTHORITY</h6>
                    <p>The institution reserves absolute authority to amend, modify, revise, suspend, or replace any policy, rule, procedure, or academic regulation at any time in response to legal requirements, regulatory directives, academic improvements, or operational considerations, and students expressly acknowledge that such amendments shall become binding from the date of official publication. Updated policies shall supersede prior versions automatically and shall apply to all students unless otherwise specified. Publication through official channels shall constitute valid notice of policy changes, and students are responsible for reviewing updates regularly. Continued enrollment after policy revision shall constitute acceptance of updated provisions. Transitional arrangements may be introduced at institutional discretion where major changes occur. Institutional interpretation of policy provisions shall be final and binding. This section ensures governance flexibility and regulatory compliance.</p>

                    <h6>SECTION 22 — LEGAL JURISDICTION</h6>
                    <p>All disputes or legal proceedings arising from the student's relationship with the institution shall fall exclusively under the jurisdiction of courts located in the area of the institution's registered administrative office, and students expressly agree not to initiate proceedings in any other jurisdiction unless required by law. Applicable law governing interpretation of institutional policies shall be that of the designated jurisdiction. Students shall attempt to resolve disputes through institutional grievance mechanisms before initiating legal action. Institutional records, logs, and official documents shall constitute primary evidence in any dispute. This section establishes jurisdictional clarity and ensures consistent legal interpretation.</p>

                    <h6>SECTION 23 — BINDING DECLARATION CLAUSE</h6>
                    <p>By enrolling, making payment, accessing resources, or participating in any institutional activity, the student formally declares that they have read, understood, and accepted all institutional terms, policies, and regulations and agree to be bound by them throughout the duration of their association with the institution and thereafter wherever institutional records or certifications apply. Students acknowledge that acceptance of admission constitutes legally valid consent to all institutional provisions and waive any claim based on alleged misunderstanding or lack of awareness of policies once such policies have been made available. Institutional records of enrollment or participation shall constitute conclusive evidence of acceptance, and no separate signature shall be required for enforceability unless specifically requested. This declaration represents the complete and final agreement governing the student's relationship with the institution and supersedes all prior representations or understandings.</p>
                </div>
                <p id="termsEndMarker" class="border-top pt-2 mt-3 text-muted small">— End of Terms &amp; Conditions —</p>
            </div>
            <div class="modal-footer">
                <p class="me-auto mb-0 text-muted small" id="termsScrollHint">Please scroll to the bottom to enable the acceptance checkbox.</p>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
(function() {
    var termsModal = document.getElementById('termsModal');
    var termsModalBody = document.getElementById('termsModalBody');
    var termsCheckbox = document.getElementById('termsCheckbox');
    var termsRead = false;

    function updateSubmitButton() {
        var submitBtn = document.getElementById('submitBtn');
        if (!submitBtn) return;
        if (termsCheckbox && termsCheckbox.checked) {
            submitBtn.disabled = false;
        } else {
            submitBtn.disabled = true;
        }
    }

    function onTermsScrolledToBottom() {
        if (!termsModalBody || termsRead) return;
        var el = termsModalBody;
        var isBottom = el.scrollHeight - el.scrollTop <= el.clientHeight + 20;
        if (isBottom) {
            termsRead = true;
            if (termsCheckbox) termsCheckbox.disabled = false;
            var hint = document.getElementById('termsScrollHint');
            if (hint) hint.textContent = 'You have read the terms. You may now close this and check the box to accept.';
        }
    }

    if (termsModalBody) {
        termsModalBody.addEventListener('scroll', onTermsScrolledToBottom);
    }

    if (termsModal) {
        termsModal.addEventListener('show.bs.modal', function() {
            termsRead = false;
            if (termsCheckbox) {
                termsCheckbox.checked = false;
                termsCheckbox.disabled = true;
            }
            var hint = document.getElementById('termsScrollHint');
            if (hint) hint.textContent = 'Please scroll to the bottom to enable the acceptance checkbox.';
            updateSubmitButton();
        });
    }

    if (termsCheckbox) {
        termsCheckbox.addEventListener('change', updateSubmitButton);
    }

    document.addEventListener('DOMContentLoaded', function() {
        var submitBtn = document.getElementById('submitBtn');
        if (submitBtn) submitBtn.disabled = true;
        updateSubmitButton();
        var form = document.getElementById('registrationForm');
        if (form && termsCheckbox) {
            form.addEventListener('submit', function(e) {
                if (!termsCheckbox.checked) {
                    e.preventDefault();
                    return false;
                }
            });
        }
    });

    window.applyTermsCheckboxVisibility = function() {
        var row = document.getElementById('termsCheckboxRow');
        var btn = document.getElementById('submitBtn');
        if (row && btn) {
            var style = window.getComputedStyle(btn);
            row.style.display = (style.display !== 'none' && style.visibility !== 'hidden') ? 'block' : 'none';
        }
    };

    document.addEventListener('DOMContentLoaded', function() {
        if (typeof window.applyTermsCheckboxVisibility === 'function') window.applyTermsCheckboxVisibility();
    });
})();
</script>
