<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>ID Card - {{ $convertedLead->name }}</title>
    <style>
        body {
            font-family: "DejaVu Sans", sans-serif;
            margin: 0;
            padding: 0;
            position: relative;
        }

        .background-image,
        .background-image-back {
            position: absolute;
            top: 0;
            left: 0;
            width: 210mm;   /* A4 width */
            height: 297mm;  /* A4 height */
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            z-index: -1;
        }

        .content {
            position: relative;
            z-index: 2;
            padding: 30px;
            padding-top: 250px;
        }

        /* Circle photo container for mPDF */
        .photo-container {
            position: absolute;
            top: 40%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
            z-index: 3;
        }

        .circle-photo {
            width: 350px;
            height: 350px;
            border-radius: 50%;
            border: 6px solid #fff;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
            margin: 0 auto;
            background-color: #fff;
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
        }

        .text-container {
            position: absolute;
            top: 65%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
            z-index: 3;
            margin-top: 80px;
        }

        .student-name {
            font-size: 40px;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
        }

        .register-number {
            font-size: 30px;
            font-weight: bold;
            color: #666;
            margin-bottom: 15px;
        }

        .course-info {
            font-size: 20px;
            color: #555;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <!-- First Page - Front -->
    <div class="background-image" style="background-image: url('data:image/png;base64,{{ base64_encode(file_get_contents(public_path("assets/images/bg-front.png"))) }}');"></div>
    <div class="content">
        <!-- Photo Circle -->
        <div class="photo-container">
            @if($circularImagePath)
                <div class="circle-photo" style="background-image: url('{{ public_path($circularImagePath) }}');"></div>
            @elseif($convertedLead->leadDetail && $convertedLead->leadDetail->passport_photo)
                <div class="circle-photo" style="background-image: url('{{ public_path('storage/' . $convertedLead->leadDetail->passport_photo) }}');"></div>
            @endif
        </div>

        <!-- Text Container -->
        <div class="text-container">
            <div class="student-name">{{ $convertedLead->name }}</div>
            @if($convertedLead->register_number)
                <div class="register-number">{{ $convertedLead->register_number }}</div>
            @endif
            <div class="course-info">{{ $convertedLead->course->title ?? '-' }}</div>
        </div>
    </div>

    <div class="page-break"></div>

    <!-- Second Page - Back -->
    <div class="background-image-back" style="background-image: url('data:image/png;base64,{{ base64_encode(file_get_contents(public_path("assets/images/bg-back.png"))) }}');"></div>
    <div class="content">
        <p>Academic Assistant: {{ $convertedLead->academicAssistant->name ?? '-' }}</p>
        <p>Generated by: {{ $convertedLead->createdBy->name ?? '-' }}</p>
    </div>
</body>
</html>
