<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ConvertedStudentMentorDetail extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'converted_student_id',
        'application_number',
        'subject_id',
        'registration_status',
        'technology_side',
        'student_status',
        'call_1',
        'app',
        'whatsapp_group',
        'telegram_group',
        'problems',
        'call_2',
        'mentor_live_1',
        'first_live',
        'first_exam_registration',
        'first_exam',
        'call_3',
        'mentor_live_2',
        'second_live',
        'second_exam',
        'call_4',
        'mentor_live_3',
        'model_exam_live',
        'model_exam',
        'practical',
        'call_5',
        'mentor_live_4',
        'self_registration',
        'call_6',
        'assignment',
        'exam_fees',
        'pcp_class',
        'call_7',
        'practical_record',
        'mock_test',
        'call_8',
        'id_card',
        'practical_hall_ticket',
        'admit_card',
        'call_9',
        'particle_exam',
        'theory_hall_ticket',
        'mentor_live_5',
        'call_10',
        'exam_subject_1',
        'exam_subject_2',
        'exam_subject_3',
        'exam_subject_4',
        'exam_subject_5',
        'exam_subject_6',
        // E-School and Eduthanzeel specific fields
        'screening_date',
        'screening_officer',
        'class_time',
        'tutor_phone_number',
        'class_status',
        'first_pa',
        'first_pa_mark',
        'feedback_call_1',
        'first_pa_remarks',
        'second_pa',
        'second_pa_mark',
        'feedback_call_2',
        'second_pa_remarks',
        'third_pa',
        'third_pa_mark',
        'feedback_call_3',
        'third_pa_remarks',
        'certification_exam',
        'certification_exam_mark',
        'course_completion_feedback',
        'certificate_collection',
        'continuing_studies',
        'reason',
        // Data Science specific fields
        'orientation_class_date',
        'class_start_date',
        'class_end_date',
        'whatsapp_group_status',
        'first_month_exam_date',
        'first_month_marks',
        'first_month_feedback',
        'second_month_exam_date',
        'second_month_marks',
        'second_month_feedback',
        'ai_workshop_attendance',
        'deep_learning_workshop_attendance',
        'graphic_design_session_attendance',
        'copy_writing_session_attendance',
        'third_month_exam_date',
        'third_month_marks',
        'third_month_feedback',
        'initial_project_start_date',
        'initial_project_end_date',
        'initial_project_marks',
        'initial_project_feedback',
        'fourth_month_exam_date',
        'fourth_month_marks',
        'fourth_month_feedback',
        'mock_test_date',
        'mock_test_marks',
        'mock_test_feedback',
        'mock_interview_date',
        'mock_interview_marks',
        'mock_interview_feedback',
        'final_project_start_date',
        'final_project_end_date',
        'final_project_marks',
        'final_project_feedback',
        'data_science_workshop_attendance',
        'total_class',
        'total_present',
        'total_absent',
        'final_certificate_examination_date',
        'certificate_examination_marks',
        'final_interview_date',
        'interview_marks',
        'certificate_distribution_date',
        'experience_certificate_distribution_date',
        'completed_cancelled_date',
        'cancelled_date',
        'first_term_internship_exam_date',
        'first_term_internship_exam_marks',
        'first_term_internship_exam_feedback',
        'final_internship_certification_exam_date',
        'final_internship_certification_exam_marks',
        'final_internship_certification_exam_feedback',
        'remarks',
        // UG/PG specific fields
        'online_registration_date',
        'admission_form_issued_date',
        'admission_form_returned_date',
        'document_verification_status',
        'verification_completed_date',
        'id_card_issued_date',
        'first_year_result_declaration_date',
        'second_year_result_declaration_date',
        'third_year_result_declaration_date',
        'all_online_result_publication_date',
        'certificate_issued_date',
        'certificate_distribution_mode',
        'courier_tracking_number',
        'online_result_publication_date',
        'certificate_publication_date',
        'remarks_internal_notes',
    ];

    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
        'screening_date' => 'date',
        'class_time' => 'datetime',
        'orientation_class_date' => 'date',
        'class_start_date' => 'date',
        'class_end_date' => 'date',
        'first_month_exam_date' => 'date',
        'second_month_exam_date' => 'date',
        'third_month_exam_date' => 'date',
        'initial_project_start_date' => 'date',
        'initial_project_end_date' => 'date',
        'fourth_month_exam_date' => 'date',
        'mock_test_date' => 'date',
        'mock_interview_date' => 'date',
        'final_project_start_date' => 'date',
        'final_project_end_date' => 'date',
        'final_certificate_examination_date' => 'date',
        'final_interview_date' => 'date',
        'certificate_distribution_date' => 'date',
        'experience_certificate_distribution_date' => 'date',
        'completed_cancelled_date' => 'date',
        'first_term_internship_exam_date' => 'date',
        'final_internship_certification_exam_date' => 'date',
        'cancelled_date' => 'date',
        // UG/PG specific date fields
        'online_registration_date' => 'date',
        'admission_form_issued_date' => 'date',
        'admission_form_returned_date' => 'date',
        'verification_completed_date' => 'date',
        'id_card_issued_date' => 'date',
        'first_year_result_declaration_date' => 'date',
        'second_year_result_declaration_date' => 'date',
        'third_year_result_declaration_date' => 'date',
        'all_online_result_publication_date' => 'date',
        'certificate_issued_date' => 'date',
        'online_result_publication_date' => 'date',
        'certificate_publication_date' => 'date',
    ];

    // Relationships
    public function convertedStudent()
    {
        return $this->belongsTo(ConvertedLead::class, 'converted_student_id');
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }
}
